services:
  site:
    build:
      context: .
      args:
        - GIT_REPO=https://github.com/isaiasfontes/site.git
        - GIT_BRANCH=main
    image: ifconnect/site:latest
    restart: unless-stopped
